CREATE TABLE Account(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    code CHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);